//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSys.Shared.Core.Domain.Impl {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSys.Shared.Core.Domain.Impl.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {PropertyValue} não é um E-mail válido..
        /// </summary>
        public static string Geral_Mensagem_Email_Invalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Email_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {PropertyName} não pode ser vazio..
        /// </summary>
        public static string Geral_Mensagem_Erro_Campo_null {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_Campo_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {PropertyName} não é um data válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_DataInvalida {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {PropertyName} não contém um valor válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_DecimalInvalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_DecimalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um registro com o nome informado..
        /// </summary>
        public static string Geral_Mensagem_Erro_NomeDuplicado {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_NomeDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {PropertyName} não é um número válida.
        /// </summary>
        public static string Geral_Mensagem_Erro_NumeroInvalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_NumeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho do campo {PropertyName} está fora do permitido..
        /// </summary>
        public static string Geral_Mensagem_Erro_Tamanho_Campo {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Erro_Tamanho_Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login e/ou senha informados são inválidos.
        /// </summary>
        public static string Geral_Mensagem_Login_Invalido {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Login_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação concluída com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro atualizado com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Alteracao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Alteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro removido com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Exclusao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Exclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro incluído com sucesso..
        /// </summary>
        public static string Geral_Mensagem_Sucesso_Inclusao {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Sucesso_Inclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário desativado, entre em contato com o administrador.
        /// </summary>
        public static string Geral_Mensagem_Usuario_Desativado {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Usuario_Desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não possui perfil definido, entre em contato com o administrador.
        /// </summary>
        public static string Geral_Mensagem_Usuario_Sem_Perfil {
            get {
                return ResourceManager.GetString("Geral_Mensagem_Usuario_Sem_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo Booleano Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Boolean {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo Data Inválida..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_DateTime {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo Decimal Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Decimal {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo Double Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Double {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo inteiro Inválido. .
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Int {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na validação. Campo Inteiro de 64Bits Inválido..
        /// </summary>
        public static string Shared_Mensagem_Erro_String_To_Int64 {
            get {
                return ResourceManager.GetString("Shared_Mensagem_Erro_String_To_Int64", resourceCulture);
            }
        }
    }
}
