// <auto-generated />
using FiveSys.Core.Retaguarda.Domain.Admin.Enum;
using FiveSysRetaguarda.Infrastructure.Data.Admin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FiveSysRetaguarda.Infrastructure.Data.Admin.Migrations
{
    [DbContext(typeof(RetaguardaContextAdmin))]
    [Migration("20180214134132_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiveSys.Core.Retaguarda.Domain.Admin.Entity.Parametro", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .HasMaxLength(100);

                    b.Property<bool>("Excluido");

                    b.Property<string>("Nome");

                    b.Property<int>("Tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("FiveSys.Core.Retaguarda.Domain.Admin.Entity.Ramo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Excluido");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Ramos");
                });

            modelBuilder.Entity("FiveSys.Core.Retaguarda.Domain.Admin.Entity.TipoCliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Excluido");

                    b.HasKey("Id");

                    b.ToTable("TiposCliente");
                });

            modelBuilder.Entity("FiveSys.Core.Retaguarda.Domain.Admin.Entity.TipoIdentificacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Excluido");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TiposIdentificacao");
                });
#pragma warning restore 612, 618
        }
    }
}
