// <auto-generated />
using FiveSys.Retaguarda.Core.Domain.Admin.Enum;
using FiveSys.Retaguarda.Infrastructure.Data.Admin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace FiveSys.Retaguarda.Infrastructure.Data.Admin.Migrations
{
    [DbContext(typeof(RetaguardaAdminContext))]
    [Migration("20180323163841_RecriaBancoDados")]
    partial class RecriaBancoDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime>("Cadastro");

                    b.Property<bool>("CasaPropria");

                    b.Property<decimal?>("Limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal?>("Pontos");

                    b.Property<string>("Referencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Regiao");

                    b.Property<decimal?>("Renda");

                    b.Property<bool>("SituacaoCadastral");

                    b.Property<string>("TipoClienteId");

                    b.Property<int>("TipoPessoa");

                    b.Property<DateTime?>("UltimaCompra");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<int>("TipoPessoa");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Email", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("MetadataId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Endereco", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Cep")
                        .HasMaxLength(9);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("CodigoMunicipio");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100);

                    b.Property<int?>("Ibge")
                        .HasMaxLength(100);

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MetadataId")
                        .HasMaxLength(36);

                    b.Property<int?>("Numero");

                    b.Property<int?>("Uf");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Fornecedor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int?>("Agencia");

                    b.Property<bool>("AssistenciaTecnica");

                    b.Property<int?>("Banco");

                    b.Property<DateTime>("Cadastro");

                    b.Property<string>("Cnae");

                    b.Property<int?>("Conta");

                    b.Property<string>("HomePage")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100);

                    b.Property<int>("Numero");

                    b.Property<string>("Obs");

                    b.Property<int>("TipoPessoa");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Fornecedores");

                    b.HasDiscriminator<int>("TipoPessoa");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Identificacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .HasMaxLength(100);

                    b.Property<string>("MetadataId")
                        .HasMaxLength(36);

                    b.Property<bool>("Status");

                    b.Property<string>("TipoIdentificacaoId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("TipoIdentificacaoId");

                    b.ToTable("Identificacoes");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Loja", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("Cadastro");

                    b.Property<string>("Cnae")
                        .HasMaxLength(30);

                    b.Property<string>("Cnpj")
                        .IsRequired();

                    b.Property<bool>("ContribuinteIpi");

                    b.Property<int?>("Crt")
                        .IsRequired();

                    b.Property<DateTime?>("Fundacao");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired();

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired();

                    b.Property<bool>("MicroempresaEstadual");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Numero");

                    b.Property<bool>("OptanteSimples");

                    b.Property<bool>("OptanteSuperSimples");

                    b.Property<bool>("PermiteCreditoIcms");

                    b.Property<string>("RamoId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100);

                    b.Property<int>("SequenciaLnf");

                    b.Property<int>("SequencialCte");

                    b.Property<int>("SeriEnf");

                    b.Property<int>("SerieCte");

                    b.Property<decimal?>("SimplesNacional");

                    b.Property<bool>("SubstitutoTributario");

                    b.Property<decimal?>("TaxaIpi");

                    b.Property<decimal?>("TaxaPis");

                    b.Property<decimal?>("Taxacofins");

                    b.Property<string>("Titular")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("RamoId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Marca", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Parametro", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .HasMaxLength(100);

                    b.Property<string>("Nome");

                    b.Property<int>("Tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Ramo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Ramos");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Tara", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Peso");

                    b.HasKey("Id");

                    b.ToTable("Taras");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Telefone", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("MetadataId")
                        .HasMaxLength(36);

                    b.Property<string>("Numero")
                        .HasMaxLength(15);

                    b.Property<int?>("Tipo")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoCliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TiposCliente");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoIdentificacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TiposIdentificacao");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoPreco", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TiposPreco");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoProduto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TiposProduto");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Unidade", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("Admissao");

                    b.Property<decimal?>("Comissao");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11);

                    b.Property<bool>("ExpirarSenha");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Observacao");

                    b.Property<string>("PerfilId");

                    b.Property<string>("Rg")
                        .HasMaxLength(15);

                    b.Property<string>("Senha")
                        .HasMaxLength(255);

                    b.Property<bool>("SenhaTemporaria");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.PessoaFisica", b =>
                {
                    b.HasBaseType("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Cliente");

                    b.Property<string>("Conjuge")
                        .HasMaxLength(255);

                    b.Property<string>("Cpf")
                        .HasMaxLength(14);

                    b.Property<DateTime?>("Emissao");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100);

                    b.Property<int?>("EstadoCivil");

                    b.Property<string>("Filiacao")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Nascimento");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(3);

                    b.Property<string>("Profissao")
                        .HasMaxLength(100);

                    b.Property<string>("Rg")
                        .HasMaxLength(15);

                    b.Property<int?>("Sexo");

                    b.Property<int?>("UfOrgaoEmissor");

                    b.ToTable("PessoaFisica");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.PessoaJuridica", b =>
                {
                    b.HasBaseType("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Cliente");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18);

                    b.Property<DateTime?>("Fundacao");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20);

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20);

                    b.Property<string>("Titular")
                        .HasMaxLength(255);

                    b.ToTable("PessoaJuridica");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.PessoaFisicaFornecedor", b =>
                {
                    b.HasBaseType("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Fornecedor");

                    b.Property<string>("Conjuge")
                        .HasMaxLength(255);

                    b.Property<string>("Cpf")
                        .HasMaxLength(14);

                    b.Property<DateTime?>("Emissao");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100);

                    b.Property<int?>("EstadoCivil");

                    b.Property<string>("Filiacao")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Nascimento");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(3);

                    b.Property<string>("Profissao")
                        .HasMaxLength(100);

                    b.Property<string>("Rg")
                        .HasMaxLength(15);

                    b.Property<int?>("Sexo");

                    b.Property<int?>("UfOrgaoEmissor");

                    b.ToTable("PessoaFisicaFornecedor");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.PessoaJuridicaFornecedor", b =>
                {
                    b.HasBaseType("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Fornecedor");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18);

                    b.Property<DateTime?>("Fundacao");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20);

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20);

                    b.Property<string>("Titular")
                        .HasMaxLength(255);

                    b.ToTable("PessoaJuridicaFornecedor");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Cliente", b =>
                {
                    b.HasOne("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteId");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Identificacao", b =>
                {
                    b.HasOne("FiveSys.Retaguarda.Core.Domain.Admin.Entity.TipoIdentificacao", "TipoIdentificacao")
                        .WithMany("Identificacoes")
                        .HasForeignKey("TipoIdentificacaoId");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Loja", b =>
                {
                    b.HasOne("FiveSys.Retaguarda.Core.Domain.Admin.Entity.Ramo", "Ramo")
                        .WithMany()
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
