// <auto-generated />
using FiveSys.Retaguarda.Core.Domain.Acesso.Enum;
using FiveSys.Retaguarda.Infrastructure.Data.Acesso;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FiveSys.Retaguarda.Infrastructure.Data.Acesso.Migrations
{
    [DbContext(typeof(RetaguardaAcessoContext))]
    partial class RetaguardaAcessoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Acesso.Entity.Perfil", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Acesso.Entity.Permissao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<int>("Acoes");

                    b.Property<int>("Funcionalidade");

                    b.Property<string>("PerfilId");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("FiveSys.Retaguarda.Core.Domain.Acesso.Entity.Permissao", b =>
                {
                    b.HasOne("FiveSys.Retaguarda.Core.Domain.Acesso.Entity.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId");
                });
#pragma warning restore 612, 618
        }
    }
}
